### PR TITLE
Xoa deploy improvements

### PR DESCRIPTION
**Pull request by julien-f**

### CODE REVIEW

**Review by benjamreis — APPROVED** [review]

**Comment by stormi** [comment]
What's the target release? Looks like fixes for the current release of XCP-ng (8.2)?

**Comment by julien-f** [comment]
The changes are related to the XO appliance itself, regardless of the XCP-ng version.

**Comment by stormi** [comment]
My question is about what to do with these changes, wait for next XCP-ng release to include them (in which case merge to master is enough), or update the current xcp-ng-release-config RPM with it as an update to all 8.2 users.

**Comment by julien-f** [comment]
IMHO, the fix may be necessary in some cases but I wasn't able to reproduce it, and the change is a minor info to users.

I don't think there's any urgency.

**Comment by stormi** [comment]
Ok, then I'll not start the update process for now. We can still backport later if needed.

**Pull request merged**
