### PR TITLE
feat(XOA deploy): also wait for IPv6

### PR DESCRIPTION
**Pull request by pdonias**
Wait for both IPv4 and IPv6 from XAPI if available and let the user choose
which one to be redirected to.

Signed-off-by: Pierre Donias <pierre.donias@gmail.com>

Redirect to IPv6 checkbox

### CODE REVIEW

**Review by benjamreis — APPROVED** [review]

**Comment by benjamreis** [comment]
To be merged with everything IPv6.

**Comment by benjamreis** [comment]
The XOA deploy script on the XCP-ng web page used to wait for the deployed XOA IP before redirecting to it.
Since we want to support IPv6 in dom0 in the future, the deploy script needs to wait for either an IPv4 or a non local IPv6.
Therefore we look in the xenstore for `0/ip` and `0/ipv6/{n}` where n is an integer and make sure `0/ipv6/n` doesn't start with `fe80` to ignore local IPv6.

**Comment by stormi** [comment]
Could we find a better PR name to reflect this? And what about the context and why of the first commit?

**Comment by stormi** [comment]
Another question that is raised by these two commits. Looks like first commit is necessary in XCP-ng 8.2 (well, I can only guess with the little information I have in the PR). The second one I don't know, but ipv6 support is not planned in 8.2 at the moment. However maybe it works without the added ipv6 support to the interface management, for all I know. 

So what are the targets?

**Comment by stormi** [comment]
Ping

**Comment by stormi** [comment]
So, there was no answer and since then, on master, XO lite replaced the current page and deploy script.

This will likely need to be done in XO lite's quick deploy support directly.

However, I'm renewing my question: what was the context and the goal of the first commit, which changes the URL from HTTP to HTTPS? I've asked about it but I still don't know. It may be important, and as I tried to explain in my previous comment, depending on the answer it might be a candidate for applying to XCP-ng 8.2.

**Comment by stormi** [comment]
Part of this PR was merged to branch 8.2 as https://github.com/xcp-ng/xcp-ng-release/pull/35

The rest (IPv6 support) is already included in other code repositories for XOA deploy code. The current master branch doesn't have quick deploy at all. It will likely come back through XO lite in some form. When this is done, then we'll likely use the code that supports IPv6.

Thus, closing.

**Pull request closed without merging**
